### PR TITLE
Hide volume column in portfolio pool pages

### PR DESCRIPTION
**Pull request by agualis**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Hide volume column in portfolio pool pages

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by agualis** [comment]
@pkattera APR column has a hadcoded width of 220: 

https://github.com/balancer/frontend-v2/blob/6086c8121caa2dae48256066085c99390607fe22/src/components/tables/PoolsTable/PoolsTable.vue#L197

Maybe we could conditionally reduce it for the portfolio tables to get some extra space?

**Review by garethfuller — CHANGES_REQUESTED** [review]
There is a big unnecessary gap after the pool value column. 
Screenshot 2023-05-23 at 09 09 08

**Comment by agualis** [comment]
> There is a big unnecessary gap after the pool value column. Screenshot 2023-05-23 at 09 09 08

I commented that in a message above:
https://github.com/balancer/frontend-v2/pull/3404#issuecomment-1557078956

Should we reduce the hard-coded 220 size in both the main pool page and the portfolio page? Do you know @garethfuller or @pkattera why that column had that concrete big width?

**Review by garethfuller — APPROVED** [review]
Looks like we could actually shrink the column width on the home page too. Unless I'm missing something, I guess you could just set it to 150 everywhere, and let's see if there are repercussions.

**Comment by pkattera** [comment]
Yeah, I'm comfortable reducing the size. At 140px, we account for triple digit APRs:

CleanShot 2023-05-23 at 10 54 14@2x

and 4 digit APRs gracefully wrap down:

CleanShot 2023-05-23 at 10 53 10@2x

**Comment by agualis** [comment]
I just set fixed width of 150 and we can always rescue [this commit](https://github.com/balancer/frontend-v2/pull/3404/commits/4653e4a61897dcc6e4221a5cdcc9aca4610ec661) if we found regressions.

**Pull request merged**
