### PR TITLE
Fix: avoid "unable to fetch token prices" errors in pool page

### PR DESCRIPTION
**Pull request by agualis**
# Description

Before this change, we were getting many `Unable to fetch token prices` errors when calling coingecko in `useHistoricalPricesQuery`. This means lots of sentry errors and annoying console.errors.

https://github.com/balancer/frontend-v2/assets/1316240/74e1c442-2eeb-4d37-a55b-6abf4667d310

The problem was that we were trying to get prices for "pool tokens" such as ` bb-a-USDT` or `bb-ag-WETH`, that are not defined in coingecko. 

The solution is excluding the addresses of those "pool tokens" from the query.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by garethfuller — CHANGES_REQUESTED** [review]
I believe this might mess up badly where these historical prices are actually used. See here: https://github.com/balancer/frontend-v2/blob/develop/src/components/contextual/pages/pool/PoolChart.vue#L187-L191

There is something about changing the amounts array based on the preMintedBptIndex so array lengths matter. I believe these prices are only used as a fallback but I'm not sure. @alter-eggo could you review this and let us know if it might break things? Can we remove the dependency on historical prices?

**Comment by garethfuller** [comment]
@alter-eggo could you review this please?

**Comment by alter-eggo** [comment]
historical prices are used to calculate properly pool's TVL. @markusbkoch wonder if we can remove this calculation and just use `snapshot.liquidity` to draw TVL chart?

**Comment by markusbkoch** [comment]
> historical prices are used to calculate properly pool's TVL. @markusbkoch wonder if we can remove this calculation and just use `snapshot.liquidity` to draw TVL chart?

Yes. There've been a few improvements to TVL computation on the subgraph since we first implemented this logic that computes TVL based on coingecko prices. So I think we can give `snapshot.liquidity` a shot. Eventually maybe the coingecko logic can be moved into the API if accuracy turns out to be an issue again?

**Review by garethfuller — APPROVED** [review]
I think this is ok to merge for now then. I'll add a ticket to Asana to remove the Coingecko dependency in the charts.

**Review by alter-eggo — APPROVED** [review]

**Pull request merged**
