### PR TITLE
hotfix: infinite loading of migration card

### PR DESCRIPTION
**Pull request by alter-eggo**
# Description
See title

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by garethfuller — COMMENTED** [review]
Does this migration flow still work anyway? Did it not break because the linear pool main token balances got too low?

**Comment by alter-eggo** [comment]
@garethfuller I'll check

**Comment by alter-eggo** [comment]
yeah seems ok
Screenshot 2023-03-17 at 21 50 29

**Review by garethfuller — APPROVED** [review]

**Comment by markusbkoch** [comment]
Not sure I understand how this fixed the issue. Does the query assume any relevant pool will be among the first 1000 to be returned by the subgraph? We have more than 1k pools, so I'm thinking this kind of pattern will eventually break for some pools, won't it? We should filter the query by pool ids whenever possible.

**Comment by alter-eggo** [comment]
@markusbkoch in api "where { id { in ..." filter is applied after a batch of pools is loaded from DynamoDB. so with first: 1000 is works correctly.
actually we had such problem in other place and @timjrobinson advised to do so

**Comment by markusbkoch** [comment]
But what if the pool of interest is eg the 1100th?

**Comment by alter-eggo** [comment]
yeah, seems api won't work in such case, am I right @timjrobinson ?

**Pull request merged**
