### PR TITLE
feat: Allow user to specify signature support 

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

Allow the user to specify whether they want to use signatures or not. Many wallet connection types don't support eth_signTypedData_v4 so it's common but not particularly easy to detect and turn off automatically.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Test a signature flow such as joining a deep pool with a wallet that supports signatures (MetaMask), check that initially it requests a relayer signature, then change the setting to off and check that the flow now requests a relayer approval tx.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by alter-eggo — APPROVED** [review]
how users will know about this feature? maybe we can notify them about it somehow

**Comment by garethfuller** [comment]
@alter-eggo I'm not sure it's something we really want to highlight, but potentially we could direct users to this setting when they experience the rejection error that happens for wallets that don't support `eth_signTypedData_v4`.

**Review by timjrobinson — APPROVED** [review]
Tested with my Gnosis safe and it worked for me joining a deep pool on polygon. It never showed a sign relayer prompt though no matter what the toggle was. 

The toggle worked correctly with my normal Metamask wallet, when I turned it off it did a relayer transaction instead of signature as expected.

**Comment by timjrobinson** [comment]
I also couldn't get the sign relayer button to appear for my Argent wallet, even though when I put breakpoints in all the spots it  checks it seems like it should be requesting a signature, not sure what's going on there.

**Pull request merged**
