### PR TITLE
Allowlist/27wst eth 7 wmatic 25 wbtc 7 usdc 18st matic 8 weth 8 dai

### PR DESCRIPTION
**Pull request by oktep**
# Description

Added new pool to allowlist.

Pool contains only mainstream coins.
Pool Name:
27wstETH-7WMATIC-25WBTC-7USDC-18stMATIC-8WETH-8DAI

Pool Address:
https://app.balancer.fi/#/polygon/pool/0x945f337307ea76fdaa2590d083423850f64e247f000100000000000000000b98

### CODE REVIEW

**Comment by oktep** [comment]
I hope, that I have done everything right. I was trying to stick to the manual.

**Comment by oktep** [comment]
@timjrobinson How can I add another reviewers?

**Comment by oktep** [comment]
@garethfuller How can I add more reviewers?

**Comment by garethfuller** [comment]
@oktep Hey, we no longer require a version bump for this type of PR, could you remove it, please?

**Review by garethfuller — APPROVED** [review]

**Pull request merged**
